name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (rama fija)
        uses: actions/checkout@v4
        with:
          ref: prueba_render  

      - name: Trigger Render deploy
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          echo "Desplegando manualmente la rama prueba_render..."
          curl -X POST "$RENDER_DEPLOY_HOOK_URL"
